'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, Heart, Menu, Search, ShoppingBag, Sparkles, Star, X } from 'lucide-react'

const products = [
  { id: 1, name: 'Kashmiri Papier Mâché Box', artisan: 'Aamina Crafts', place: 'Srinagar, Kashmir', category: 'Handicraft', price: 1850, rating: 4.9, image: 'https://images.unsplash.com/photo-1603561596112-db1d5eac8b9e?auto=format&fit=crop&w=900&q=85' },
  { id: 2, name: 'Indigo Dabu Table Runner', artisan: 'Mitti & Loom', place: 'Bagru, Rajasthan', category: 'Handloom', price: 2400, rating: 4.8, image: 'https://images.unsplash.com/photo-1616627561839-074385245ff6?auto=format&fit=crop&w=900&q=85' },
  { id: 3, name: 'Terracotta Surahi Vase', artisan: 'Ramesh Kumar', place: 'Khurja, Uttar Pradesh', category: 'Pottery', price: 1250, rating: 4.7, image: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=900&q=85' },
  { id: 4, name: 'Dokra Dancing Couple', artisan: 'Bastar Collective', place: 'Bastar, Chhattisgarh', category: 'Metalcraft', price: 3200, rating: 5, image: 'https://images.unsplash.com/photo-1577083288073-40892c0860a4?auto=format&fit=crop&w=900&q=85' },
]
const categories = [
  ['Handloom', '1,248', 'https://images.unsplash.com/photo-1610397962076-02407a169a5b?auto=format&fit=crop&w=600&q=85'],
  ['Pottery', '856', 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=600&q=85'],
  ['Woodcraft', '642', 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=600&q=85'],
  ['Jewellery', '932', 'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=600&q=85'],
]

export default function Page() {
  const [query, setQuery] = useState('')
  const [menuOpen, setMenuOpen] = useState(false)
  const [category, setCategory] = useState('All crafts')
  const [wishlist, setWishlist] = useState<number[]>([])
  const [cart, setCart] = useState(0)
  const visibleProducts = useMemo(() => products.filter(p => (category === 'All crafts' || p.category === category) && `${p.name} ${p.artisan} ${p.place} ${p.category}`.toLowerCase().includes(query.toLowerCase())), [query, category])
  const chooseCategory = (value: string) => { setCategory(value); document.getElementById('marketplace')?.scrollIntoView({ behavior: 'smooth' }) }

  return <main id="top" className="min-h-screen bg-[#fbfaf7] text-[#1d2925]">
    <div className="border-b border-[#e6e8e1] bg-[#eef4ed] px-4 py-2 text-center text-[11px] font-medium tracking-[0.14em] text-[#50685b] uppercase">Every purchase supports an artisan&apos;s livelihood · Free shipping across India</div>
    <header className="sticky top-0 z-20 border-b border-[#e7e8e2] bg-[#fbfaf7]/95 backdrop-blur-md"><div className="mx-auto flex h-[74px] max-w-[1320px] items-center gap-7 px-5 lg:px-8"><button className="lg:hidden" aria-label="Open menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button><a href="#top" className="mr-auto flex items-center gap-2.5"><span className="flex size-9 items-center justify-center rounded-full bg-[#d9704b] text-lg font-semibold text-white">क</span><span className="font-serif text-[23px] font-semibold">KalaSetu<span className="text-[#d9704b]">.</span></span></a><nav className={`${menuOpen ? 'flex' : 'hidden'} absolute left-0 top-[74px] w-full flex-col gap-5 border-b bg-[#fbfaf7] p-6 text-sm lg:static lg:flex lg:w-auto lg:flex-row lg:border-0 lg:bg-transparent lg:p-0`}><a href="#marketplace">Marketplace</a><a href="#categories">Categories</a><a href="#artisans">Artisans</a></nav><div className="hidden items-center gap-5 text-[#52635a] sm:flex"><a href="/auth" className="rounded-full border border-[#d9704b] px-4 py-2 text-xs font-bold text-[#d9704b] transition hover:bg-[#d9704b] hover:text-white">Sign in</a><button aria-label="Search" onClick={() => document.getElementById('market-search')?.focus()}><Search /></button><button aria-label="Wishlist" onClick={() => document.getElementById('marketplace')?.scrollIntoView({ behavior: 'smooth' })} className="relative"><Heart /><span className="absolute -right-2 -top-2 flex size-3.5 items-center justify-center rounded-full bg-[#d9704b] text-[9px] text-white">{wishlist.length}</span></button><button aria-label="Cart" onClick={() => alert(`${cart} item${cart === 1 ? '' : 's'} in your cart`)} className="relative"><ShoppingBag /><span className="absolute -right-2 -top-2 flex size-3.5 items-center justify-center rounded-full bg-[#d9704b] text-[9px] text-white">{cart}</span></button></div></div></header>
    <section className="mx-auto grid max-w-[1320px] items-center gap-10 px-5 pb-16 pt-12 lg:grid-cols-[1fr_0.95fr] lg:px-8 lg:pb-24 lg:pt-20"><div className="max-w-[590px]"><p className="mb-5 text-[11px] font-bold tracking-[0.2em] text-[#d9704b] uppercase">India, made by hand</p><h1 className="font-serif text-[clamp(47px,6vw,82px)] leading-[0.94] tracking-[-0.065em] text-[#20342b]">Discover India&apos;s <em className="text-[#d9704b]">handmade</em> heritage.</h1><p className="mt-7 max-w-[470px] text-[16px] leading-7 text-[#65756c]">One-of-a-kind pieces, made slowly and honestly by the hands that carry generations of craft forward.</p><a href="#marketplace" className="mt-9 inline-flex items-center gap-3 rounded-full bg-[#20342b] px-6 py-3.5 text-sm font-semibold text-white">Explore marketplace <ArrowRight /></a></div><div className="relative min-h-[390px] lg:min-h-[510px]"><div className="absolute right-0 top-0 h-[82%] w-[72%] overflow-hidden rounded-[180px_180px_14px_14px]"><img className="h-full w-full object-cover" alt="Handcrafted blue pottery" src="https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1000&q=90" /></div><div className="absolute bottom-0 left-0 h-[57%] w-[52%] overflow-hidden rounded-[14px_120px_14px_14px] border-[9px] border-[#fbfaf7]"><img className="h-full w-full object-cover" alt="Artisan weaving textile" src="https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?auto=format&fit=crop&w=800&q=90" /></div></div></section>
    <section id="marketplace" className="border-y border-[#e6e8e1] bg-white px-5 py-14 lg:px-8 lg:py-20"><div className="mx-auto max-w-[1320px]"><p className="mb-2 text-[11px] font-bold tracking-[0.18em] text-[#d9704b] uppercase">The collection</p><h2 className="font-serif text-4xl">Made to be kept.</h2><div className="my-8 flex flex-wrap gap-2"><div className="flex min-w-[260px] flex-1 items-center gap-3 rounded-full border border-[#dce3dc] bg-[#fbfaf7] px-4 py-3"><Search className="size-4" /><input id="market-search" value={query} onChange={e => setQuery(e.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder="Search crafts, products or artisans..." /></div></div><div className="mb-8 flex gap-2 overflow-x-auto">{['All crafts', 'Handloom', 'Pottery', 'Woodcraft', 'Metalcraft', 'Jewellery'].map(c => <button key={c} onClick={() => setCategory(c)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-semibold ${category === c ? 'bg-[#20342b] text-white' : 'bg-[#f1f4f0] text-[#65756c]'}`}>{c}</button>)}</div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{visibleProducts.map(p => <article key={p.id}><div className="relative aspect-[0.86] overflow-hidden rounded-xl bg-[#eef0eb]"><img className="h-full w-full object-cover" src={p.image} alt={p.name} /><button aria-label={`Add ${p.name} to wishlist`} onClick={() => setWishlist(w => w.includes(p.id) ? w.filter(id => id !== p.id) : [...w, p.id])} className="absolute right-3 top-3 rounded-full bg-white/90 p-2"><Heart className={wishlist.includes(p.id) ? 'fill-[#d9704b] text-[#d9704b]' : ''} /></button></div><h3 className="mt-4 font-serif text-xl">{p.name}</h3><p className="mt-1 text-xs text-[#78867e]">{p.artisan} · {p.place}</p><div className="mt-3 flex items-center justify-between"><span className="font-semibold">₹{p.price.toLocaleString('en-IN')}</span><button onClick={() => setCart(c => c + 1)} className="rounded-full bg-[#eef4ed] px-3 py-2 text-xs font-semibold">Add to cart</button></div><p className="mt-2 flex items-center gap-1 text-xs"><Star className="size-3 fill-[#d9704b] text-[#d9704b]" /> {p.rating}</p></article>)}</div>{visibleProducts.length === 0 && <p className="py-12 text-center text-sm text-[#78867e]">No pieces found. Try another category or search.</p>}</div></section>
    <section id="categories" className="mx-auto max-w-[1320px] px-5 py-16 lg:px-8 lg:py-24"><p className="mb-2 text-[11px] font-bold tracking-[0.18em] text-[#d9704b] uppercase">Browse by tradition</p><h2 className="mb-8 font-serif text-4xl">Find your kind of craft.</h2><div className="grid grid-cols-2 gap-3 lg:grid-cols-4 lg:gap-5">{categories.map(([name, count, image]) => <button key={name} onClick={() => chooseCategory(name)} className="group relative aspect-[0.82] overflow-hidden rounded-xl text-left"><img className="h-full w-full object-cover transition duration-500 group-hover:scale-105" src={image} alt={name} /><div className="absolute inset-0 bg-gradient-to-t from-[#17251f]/75 to-transparent" /><div className="absolute bottom-4 left-4 text-white"><h3 className="font-serif text-2xl">{name}</h3><p className="mt-1 text-[11px] text-white/75">{count} pieces</p></div></button>)}</div></section>
    <section id="artisans" className="px-5 py-16 text-center lg:px-8"><Sparkles className="mx-auto mb-4 text-[#d9704b]" /><h2 className="font-serif text-4xl">The story is in the making.</h2><p className="mx-auto mt-4 max-w-[510px] text-sm leading-6 text-[#65756c]">Meet the artisans keeping India&apos;s living traditions alive.</p></section>
    <footer className="border-t border-[#e6e8e1] px-5 py-8 text-xs text-[#78867e]"><div className="mx-auto flex max-w-[1320px] justify-between gap-4"><span className="font-serif text-base font-semibold text-[#20342b]">KalaSetu<span className="text-[#d9704b]">.</span></span><span>© 2026 KalaSetu AI · Made for makers, made for you.</span></div></footer>
  </main>
}
