import Link from 'next/link'
import { db, ensureMarketplaceSchema, hasDatabaseConnection } from '@/lib/db'
import { sql } from 'drizzle-orm'
import { AddToCartButton } from '@/components/add-to-cart-button'
import { InquiryComposer } from '@/components/inquiry-composer'
import { ReviewComposer } from '@/components/review-composer'
import { getDemoProductById, getDemoReviews } from '@/lib/demo-data'

export default async function ProductPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params

  if (!hasDatabaseConnection()) {
    const product = getDemoProductById(id)
    if (!product) {
      return <main className="min-h-screen bg-[#f7f3ec] p-8"><Link href="/buyer">Back to marketplace</Link><h1 className="mt-12 font-serif text-4xl">Product not found.</h1><p className="mt-3 text-[#68766d]">This product is unpublished, unavailable, or no longer exists.</p></main>
    }

    const reviews = getDemoReviews(id)
    const price = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(product.price)
    return <main className="min-h-screen bg-[#f7f3ec] px-5 py-8 text-[#17251f] lg:px-12"><Link href="/buyer" className="text-sm font-semibold text-[#d9704b]">← Back to marketplace</Link><div className="mx-auto mt-10 grid max-w-6xl gap-10 lg:grid-cols-2"><div className="flex min-h-[420px] items-center justify-center rounded-[2rem] bg-[#e7eee5] p-8"><img src={product.imageUrl} alt={product.name} className="max-h-[420px] rounded-2xl object-contain" /></div><article><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d9704b]">{product.category} · {product.state}</p><h1 className="mt-3 font-serif text-5xl">{product.name}</h1><p className="mt-5 text-2xl font-semibold text-[#1e503e]">{price}</p><p className="mt-6 leading-7 text-[#68766d]">{product.description}</p><p className="mt-5 text-sm">Made by <strong>{product.shopName || product.sellerName}</strong></p><div className="mt-8 flex flex-wrap gap-3"><AddToCartButton productId={product.id} /><Link href="/buyer/inquiries" className="rounded-full border border-[#d8d1c4] px-5 py-3 text-sm font-semibold">Contact seller</Link></div><p className="mt-5 text-xs text-[#68766d]">Availability: {product.availability}. Payment is not configured, so checkout will never claim a successful charge.</p><InquiryComposer sellerId={product.sellerId} productId={product.id} /><ReviewComposer productId={product.id} /></article></div><section className="mx-auto mt-10 max-w-6xl rounded-[2rem] border border-[#ddd5c7] bg-white p-7"><h2 className="font-serif text-3xl">Buyer reviews</h2>{reviews.length === 0 ? <p className="mt-4 text-sm text-[#68766d]">No reviews yet. Verified buyers can share the first note after purchase.</p> : <div className="mt-5 grid gap-4 sm:grid-cols-2">{reviews.map((review, index) => <article key={index} className="rounded-2xl bg-[#f8f5ef] p-4"><div className="flex items-center justify-between"><strong>{review.buyer_name}</strong><span className="text-[#d9704b]">{'★'.repeat(review.rating)}{'☆'.repeat(5 - review.rating)}</span></div><p className="mt-3 text-sm leading-6 text-[#68766d]">{review.body}</p><time className="mt-3 block text-xs text-[#68766d]">{new Date(review.createdAt).toLocaleDateString('en-IN')}</time></article>)}</div>}</section></main>
  }

  await ensureMarketplaceSchema()
  const result = await db.execute(sql`SELECT p.id, p.name, p.description, p.category, p.price, CASE WHEN p."imageUrl" LIKE 'blob:%' THEN '' ELSE p."imageUrl" END AS "imageUrl", p.state, p.availability, p."sellerId", COALESCE(sp."shopName", u.name) AS seller_name FROM products p LEFT JOIN seller_profiles sp ON sp."userId" = p."sellerId" LEFT JOIN "user" u ON u.id = p."sellerId" WHERE p.id = ${id} AND p.published = true LIMIT 1`)
  const product = (result as unknown as { rows?: Record<string, unknown>[] }).rows?.[0]
  if (!product) return <main className="min-h-screen bg-[#f7f3ec] p-8"><Link href="/buyer">Back to marketplace</Link><h1 className="mt-12 font-serif text-4xl">Product not found.</h1><p className="mt-3 text-[#68766d]">This product is unpublished, unavailable, or no longer exists.</p></main>
  const reviewsResult = await db.execute(sql`SELECT r.rating, r.body, r."createdAt", u.name AS buyer_name FROM reviews r LEFT JOIN "user" u ON u.id = r."buyerId" WHERE r."productId" = ${id} ORDER BY r."createdAt" DESC LIMIT 20`)
  const reviews = (reviewsResult as unknown as { rows?: Record<string, unknown>[] }).rows ?? []
  const price = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Number(product.price))
  return <main className="min-h-screen bg-[#f7f3ec] px-5 py-8 text-[#17251f] lg:px-12"><Link href="/buyer" className="text-sm font-semibold text-[#d9704b]">← Back to marketplace</Link><div className="mx-auto mt-10 grid max-w-6xl gap-10 lg:grid-cols-2"><div className="flex min-h-[420px] items-center justify-center rounded-[2rem] bg-[#e7eee5] p-8">{product.imageUrl ? <img src={String(product.imageUrl)} alt={String(product.name)} className="max-h-[420px] rounded-2xl object-contain" /> : <span className="text-sm text-[#68766d]">Seller image not provided</span>}</div><article><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d9704b]">{String(product.category)} · {String(product.state || 'India')}</p><h1 className="mt-3 font-serif text-5xl">{String(product.name)}</h1><p className="mt-5 text-2xl font-semibold text-[#1e503e]">{price}</p><p className="mt-6 leading-7 text-[#68766d]">{String(product.description)}</p><p className="mt-5 text-sm">Made by <strong>{String(product.seller_name || 'KalaSetu artisan')}</strong></p><div className="mt-8 flex flex-wrap gap-3"><AddToCartButton productId={String(product.id)} /><Link href="/buyer/inquiries" className="rounded-full border border-[#d8d1c4] px-5 py-3 text-sm font-semibold">Contact seller</Link></div><p className="mt-5 text-xs text-[#68766d]">Availability: {String(product.availability)}. Payment is not configured, so checkout will never claim a successful charge.</p><InquiryComposer sellerId={String(product.sellerId)} productId={String(product.id)} /><ReviewComposer productId={String(product.id)} /></article></div><section className="mx-auto mt-10 max-w-6xl rounded-[2rem] border border-[#ddd5c7] bg-white p-7"><h2 className="font-serif text-3xl">Buyer reviews</h2>{reviews.length === 0 ? <p className="mt-4 text-sm text-[#68766d]">No reviews yet. Verified buyers can share the first note after purchase.</p> : <div className="mt-5 grid gap-4 sm:grid-cols-2">{reviews.map((review, index) => <article key={index} className="rounded-2xl bg-[#f7f3ec] p-5"><p className="font-semibold">{'★'.repeat(Number(review.rating))}</p><p className="mt-2 text-sm leading-6 text-[#68766d]">{String(review.body)}</p><p className="mt-3 text-xs text-[#89948d]">{String(review.buyer_name || 'Buyer')}</p></article>)}</div>}</section></main>
}
